name: servarr
maintainers:
  - name: kubitodev
    url: https://kubito.dev
apiVersion: v2
appVersion: 1.1.3
version: 1.1.3
description: Kubito Servarr Helm Chart
home: https://github.com/kubitodev/helm/tree/main/charts/servarr
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - bazarr
  - lidarr
  - sonarr
  - radarr
  - readarr
  - flaresolverr
  - jellyfin
  - jellyseerr
  - qbittorrent
  - prowlarr
  - cleanuperr
sources:
  - https://github.com/Servarr
