name: traefik-cloudflared-source-ip
maintainers:
  - name: kubitodev
    url: https://kubito.dev
apiVersion: v2
appVersion: 2.10.1
version: 1.0.7
description: Kubito Traefik Cloudflared (Argo Tunnel) Real IP Helm Chart
home: https://github.com/kubitodev/helm/tree/main/charts/traefik-cloudflared-source-ip
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - cloudflare
  - cloudflared
  - middleware
  - real-ip
  - source-ip
  - argo-tunnel
  - argo
  - traefik
sources:
  - https://github.com/kubitodev/traefik-cloudflared-source-ip

dependencies:
  - condition: global.cloudflaredEnabled
    name: cloudflared
    repository: https://charts.kubito.dev
    # https://github.com/Masterminds/semver#checking-version-constraints
    version: 1.x.x
  - condition: global.traefikEnabled
    name: traefik
    repository: https://traefik.github.io/charts
    version: 23.0.1
