{{- if and .Values.cleanuparr.enabled .Values.cleanuparr.persistence.enabled (not .Values.cleanuparr.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cleanuparr
  labels:
    app.kubernetes.io/name: cleanuparr
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- if .Values.cleanuparr.persistence.annotations }}
  annotations:
    {{- toYaml .Values.cleanuparr.persistence.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.cleanuparr.persistence.accessMode | quote }}
  {{- if .Values.cleanuparr.persistence.storageClass }}
  storageClassName: {{ .Values.cleanuparr.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cleanuparr.persistence.size | quote }}
{{- end }}
